### PR TITLE
Fixes all PSR-2 compliance issues other than index.php view lacking PHP

### PR DESCRIPTION
**Pull request by dstockto**

### CODE REVIEW

**Comment by harikt** [comment]
Version 1 will never ever see another release. So may be these commits have nothing to do. But merging.

**Comment by dstockto** [comment]
@harikt Is there a branch of this project that will be used for future release or is this project no longer maintained?

**Comment by harikt** [comment]
Actually I merged on the master. So I have reverted that merge.

This repo is no longer maintained, so no branch is maintained. 

v2 is https://github.com/auraphp/Aura.Web_Kernel/ .

And v3 there is no framework : http://auraphp.com/blog/2015/03/27/aura-3-plans/ .

There is another project http://github.com/radarphp/ which you could have a look.

**Comment by dstockto** [comment]
@harikt It might be good to update the README or CONTRIBUTING docs to indicate that this is no longer maintained and that PRs are not wanted, etc.

I'll take a look at the other repo.

**Comment by harikt** [comment]
> @harikt It might be good to update the README or CONTRIBUTING docs to indicate that this is no longer maintained

Yes, I agree with you. May be link to https://groups.google.com/d/msg/auraphp/30ijuEofSvI/uGORD7bllkYJ or blog post seems good.

**Comment by dstockto** [comment]
@harikt Do you want a PR for that?

**Comment by harikt** [comment]
sure. You can send.

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by dstockto** [comment]
@harikt I've pushed up #57 to update the README for this.

**Comment by harikt** [comment]
It is again to master :-/ .

**Comment by dstockto** [comment]
Where should it be to?

**Comment by harikt** [comment]
develop branch. See https://github.com/auraphp/Aura.Framework for it is default branch.

**Pull request merged**
